version: 0.2

env:
  secrets-manager:
    SERVERLESS_ACCESS_KEY: AK1mqOrDFE16b2DsKXRG5JYIXakxcUvtue8USANHMHEFL
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - sls deploy -s dev
  post_build:
    commands:
      - echo Deployment completed on `date`
